# RNN

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.utils import to_categorical

In [ ]:
with open("/content/Dataset_RNN.txt", "r", encoding="utf-8") as f:
    data = f.read().lower()

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
print(tokenizer.word_index)

{'the': 1, 'and': 2, 'to': 3, 'i': 4, 'of': 5, 'you': 6, 'my': 7, 'that': 8, 'a': 9, 'in': 10, 'your': 11, 'he': 12, 'not': 13, 'for': 14, 'with': 15, 'his': 16, 'is': 17, 'have': 18, 'me': 19, 'it': 20, 'be': 21, 'him': 22, 'but': 23, 'as': 24, 'this': 25, 'what': 26, 'so': 27, 'we': 28, 'thou': 29, 'all': 30, 'will': 31, 'thy': 32, 'by': 33, 'are': 34, 'our': 35, 'no': 36, 'lord': 37, 'if': 38, 'shall': 39, 'do': 40, 'they': 41, 'king': 42, 'their': 43, 'them': 44, 'on': 45, 'good': 46, 'gloucester': 47, 'which': 48, 'first': 49, 'coriolanus': 50, 'thee': 51, 'menenius': 52, 'at': 53, 'queen': 54, 'now': 55, 'was': 56, 'from': 57, 'would': 58, 'when': 59, 'than': 60, 'well': 61, 'come': 62, 'then': 63, 'more': 64, 'us': 65, 'were': 66, 'her': 67, 'richard': 68, 'or': 69, 'say': 70, 'buckingham': 71, 'o': 72, 'had': 73, 'go': 74, 'marcius': 75, 'sicinius': 76, 'how': 77, 'let': 78, 'did': 79, 'one': 80, 'like': 81, 'iii': 82, 'here': 83, 'upon': 84, 'second': 85, 'hath': 86, 'make': 8

In [ ]:
input_sequences = []

for line in data.split("\n"):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram = token_list[:i+1]
        input_sequences.append(n_gram)
print(input_sequences)

[[49, 91], [137, 28], [137, 28, 645], [137, 28, 645, 188], [137, 28, 645, 188, 391], [137, 28, 645, 188, 391, 110], [137, 28, 645, 188, 391, 110, 19], [137, 28, 645, 188, 391, 110, 19, 109], [109, 109], [49, 91], [6, 34], [6, 34, 30], [6, 34, 30, 994], [6, 34, 30, 994, 246], [6, 34, 30, 994, 246, 3], [6, 34, 30, 994, 246, 3, 236], [6, 34, 30, 994, 246, 3, 236, 60], [6, 34, 30, 994, 246, 3, 236, 60, 3], [6, 34, 30, 994, 246, 3, 236, 60, 3, 1934], [994, 994], [49, 91], [49, 6], [49, 6, 103], [49, 6, 103, 392], [49, 6, 103, 392, 75], [49, 6, 103, 392, 75, 17], [49, 6, 103, 392, 75, 17, 1935], [49, 6, 103, 392, 75, 17, 1935, 393], [49, 6, 103, 392, 75, 17, 1935, 393, 3], [49, 6, 103, 392, 75, 17, 1935, 393, 3, 1], [49, 6, 103, 392, 75, 17, 1935, 393, 3, 1, 126], [28, 1483], [28, 1483, 28], [28, 1483, 28, 1483], [49, 91], [78, 65], [78, 65, 322], [78, 65, 322, 22], [78, 65, 322, 22, 2], [78, 65, 322, 22, 2, 394], [78, 65, 322, 22, 2, 394, 18], [78, 65, 322, 22, 2, 394, 18, 588], [78, 65, 32

In [ ]:
max_len = max(len(seq) for seq in input_sequences)
print(max_len)

13


In [ ]:
input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')
print(input_sequences)

[[   0    0    0 ...    0   49   91]
 [   0    0    0 ...    0  137   28]
 [   0    0    0 ...  137   28  645]
 ...
 [   0    0    0 ... 2718 6088 2858]
 [   0    0    0 ... 6088 2858   88]
 [   0    0    0 ... 2858   88 6089]]


In [ ]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]
print(X.shape)
print(y.shape)

(45229, 12)
(45229,)


In [ ]:
total_words = len(tokenizer.word_index)+1

In [ ]:
y = to_categorical(y, num_classes=total_words)

In [ ]:
model = Sequential()

model.add(Embedding(total_words, 100, input_length=max_len-1))

model.add(LSTM(150, return_sequences=True))

model.add(LSTM(100))

model.add(Dense(total_words, activation="softmax"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200
1414/1414 ━━━━━━━━━━━━━━━━━━━━ 20s 9ms/step - accuracy: 0.0354 - loss: 6.8632
Epoch 2/200
1414/1414 ━━━━━━━━━━━━━━━━━━━━ 14s 10ms/step - accuracy: 0.0463 - loss: 6.4393
Epoch 3/200
1414/1414 ━━━━━━━━━━━━━━━━━━━━ 13s 9ms/step - accuracy: 0.0649 - loss: 6.1478
Epoch 4/200
1414/1414 ━━━━━━━━━━━━━━━━━━━━ 13s 9ms/step - accuracy: 0.0805 - loss: 5.9041
Epoch 5/200
1414/1414 ━━━━━━━━━━━━━━━━━━━━ 13s 9ms/step - accuracy: 0.0923 - loss: 5.7080
Epoch 6/200
1414/1414 ━━━━━━━━━━━━━━━━━━━━ 13s 9ms/step - accuracy: 0.1012 - loss: 5.5253
Epoch 7/200
1414/1414 ━━━━━━━━━━━━━━━━━━━━ 13s 9ms/step - accuracy: 0.1090 - loss: 5.3561
Epoch 8/200
1414/1414 ━━━━━━━━━━━━━━━━━━━━ 13s 9ms/step - accuracy: 0.1151 - loss: 5.2017
Epoch 9/200
1414/1414 ━━━━━━━━━━━━━━━━━━━━ 13s 9ms/step - accuracy: 0.1211 - loss: 5.0491
Epoch 10/200
1414/1414 ━━━━━━━━━━━━━━━━━━━━ 20s 9ms/step - accuracy: 0.1265 - loss: 4.9036
Epoch 11/200
1414/1414 ━━━━━━━━━━━━━━━━━━━━ 13s 9ms/step - accuracy: 0.1299 - loss: 4.7656
Epoch 1

In [ ]:
def predict_next_word(text):

    token_list = tokenizer.texts_to_sequences([text])[0]

    token_list = pad_sequences(
        [token_list],
        maxlen=max_len-1,
        padding='pre'
    )

    predicted = np.argmax(model.predict(token_list, verbose=0))

    for word, index in tokenizer.word_index.items():
        if index == predicted:
            return word

In [ ]:
print(predict_next_word("What men of name resort to"))

shaw


In [ ]:
print(predict_next_word("At Pembroke, or at Harford-west, in"))

hastings


In [ ]:
print(predict_next_word("That in the sty of this most"))

device


In [ ]:
print(predict_next_word("Oxford, redoubted Pembroke, Sir"))

doing


In [ ]:
model.save('Shakespearean-Text-Generator-LSTM.keras')

In [19]:
import pickle
with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)