In [1]:
import pandas as pd
import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

from sklearn.preprocessing import LabelEncoder

In [2]:
questions = [
    "Hi",
    "Hello",
    "How are you?",
    "What is your name?",
    "Who created you?",
    "What can you do?",
    "How old are you?",
    "Where are you from?",
    "What time is it?",
    "What is today's date?",
    "Tell me a joke",
    "What is AI?",
    "What is Machine Learning?",
    "What is Python?",
    "What is Java?",
    "What is HTML?",
    "What is CSS?",
    "What is JavaScript?",
    "What is the capital of India?",
    "What is the capital of the USA?",
    "Who is the Prime Minister of India?",
    "What is the largest planet?",
    "What is the fastest animal?",
    "What is 5 + 7?",
    "What is the square root of 64?",
    "Thank you",
    "Bye",
    "Good morning",
    "Good night",
    "I love you"
]

answers = [
    "Hello! How can I help you today?",
    "Hi there! Nice to meet you.",
    "I'm doing great! Thanks for asking. How about you?",
    "My name is ChatBot.",
    "I was created by a developer to assist users.",
    "I can answer questions, chat with you, and provide information.",
    "I don't have an age because I'm a computer program.",
    "I exist in the digital world!",
    "Sorry, I can't check the current time unless connected to a clock or API.",
    "I can't access today's date unless connected to a calendar API.",
    "Why don't programmers like nature? It has too many bugs!",
    "AI stands for Artificial Intelligence. It enables computers to perform tasks that usually require human intelligence.",
    "Machine Learning is a branch of AI where computers learn from data to make predictions or decisions.",
    "Python is a popular programming language known for its simplicity and versatility.",
    "Java is an object-oriented programming language widely used for web, mobile, and enterprise applications.",
    "HTML is the standard language used to create web pages.",
    "CSS is used to style and design HTML web pages.",
    "JavaScript is a programming language used to make web pages interactive.",
    "New Delhi is the capital of India.",
    "Washington, D.C. is the capital of the United States.",
    "Narendra Modi is the Prime Minister of India.",
    "Jupiter is the largest planet in our solar system.",
    "The peregrine falcon is the fastest animal when diving.",
    "5 + 7 = 12.",
    "The square root of 64 is 8.",
    "You're welcome! Happy to help.",
    "Goodbye! Have a wonderful day.",
    "Good morning! Hope you have a fantastic day.",
    "Good night! Sleep well and take care.",
    "Thank you! I'm happy to chat with you and help however I can."
]

In [3]:
encoder = LabelEncoder()
y = encoder.fit_transform(answers)
print(y)

[ 7  8 14 19 13  9 11 12 23 10 28  1 18 22 15  6  2 16 21 27 20 17 25  0
 26 29  5  3  4 24]


In [4]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(questions)
X = tokenizer.texts_to_sequences(questions)
print(X)

[[12], [13], [7, 6, 3], [1, 2, 14, 15], [8, 16, 3], [1, 17, 3, 18], [7, 19, 6, 3], [20, 6, 3, 21], [1, 22, 2, 23], [1, 2, 24, 25], [26, 27, 28, 29], [1, 2, 30], [1, 2, 31, 32], [1, 2, 33], [1, 2, 34], [1, 2, 35], [1, 2, 36], [1, 2, 37], [1, 2, 4, 9, 5, 10], [1, 2, 4, 9, 5, 4, 38], [8, 2, 4, 39, 40, 5, 10], [1, 2, 4, 41, 42], [1, 2, 4, 43, 44], [1, 2, 45, 46], [1, 2, 4, 47, 48, 5, 49], [50, 3], [51], [11, 52], [11, 53], [54, 55, 3]]


In [5]:
max_length = max(len(i) for i in X)
X = pad_sequences(X, maxlen=max_length, padding="post")
print(X)

[[12  0  0  0  0  0  0]
 [13  0  0  0  0  0  0]
 [ 7  6  3  0  0  0  0]
 [ 1  2 14 15  0  0  0]
 [ 8 16  3  0  0  0  0]
 [ 1 17  3 18  0  0  0]
 [ 7 19  6  3  0  0  0]
 [20  6  3 21  0  0  0]
 [ 1 22  2 23  0  0  0]
 [ 1  2 24 25  0  0  0]
 [26 27 28 29  0  0  0]
 [ 1  2 30  0  0  0  0]
 [ 1  2 31 32  0  0  0]
 [ 1  2 33  0  0  0  0]
 [ 1  2 34  0  0  0  0]
 [ 1  2 35  0  0  0  0]
 [ 1  2 36  0  0  0  0]
 [ 1  2 37  0  0  0  0]
 [ 1  2  4  9  5 10  0]
 [ 1  2  4  9  5  4 38]
 [ 8  2  4 39 40  5 10]
 [ 1  2  4 41 42  0  0]
 [ 1  2  4 43 44  0  0]
 [ 1  2 45 46  0  0  0]
 [ 1  2  4 47 48  5 49]
 [50  3  0  0  0  0  0]
 [51  0  0  0  0  0  0]
 [11 52  0  0  0  0  0]
 [11 53  0  0  0  0  0]
 [54 55  3  0  0  0  0]]


In [6]:
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=16))
model.add(LSTM(32))
model.add(Dense(len(np.unique(y)), activation="softmax"))

In [7]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [8]:
model.fit(X, y, epochs=300)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - accuracy: 0.0000e+00 - loss: 3.4017
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.0333 - loss: 3.4010
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.0333 - loss: 3.4003
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.0333 - loss: 3.3996
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.0667 - loss: 3.3989
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.0667 - loss: 3.3982
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.0333 - loss: 3.3975
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.0667 - loss: 3.3968
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.0667 - loss: 3.3961
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.1000 - loss: 3.3953
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.1333 - loss: 3.3946
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.1667 - 

In [9]:
question = ["What is AI?"]
test = tokenizer.texts_to_sequences(question)
test = pad_sequences( test, maxlen=max_length, padding="post")

In [10]:
prediction = model.predict(test)
index = np.argmax(prediction)
print(index)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 251ms/step
1


In [11]:
answer = encoder.inverse_transform([index])
print(answer[0])

AI stands for Artificial Intelligence. It enables computers to perform tasks that usually require human intelligence.


In [12]:
while True:

    question = input("You : ")

    if question.lower() == "exit":
        break

    test = tokenizer.texts_to_sequences([question])

    test = pad_sequences(
        test,
        maxlen=max_length,
        padding="post"
    )

    prediction = model.predict(test, verbose=0)

    index = np.argmax(prediction)

    answer = encoder.inverse_transform([index])

    print("Bot :", answer[0])

You : exit


In [ ]:
model.save('Chatbot.keras')

In [ ]:
import pickle


with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

with open("encoder.pkl", "wb") as f:
    pickle.dump(encoder, f)